# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests

class Ui_Form(object):
    def setupUi(self, Form, users):
        Form.setObjectName("Form")
        Form.resize(1110, 691)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(len(users))  

        item = QtWidgets.QTableWidgetItem()
        item.setText("Name")
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Nationality")
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("ID")
        self.tableWidget.setHorizontalHeaderItem(2, item)

        for row, user in enumerate(users):
            item = QtWidgets.QTableWidgetItem()
            item.setText(user['Name'])
            self.tableWidget.setItem(row, 0, item)

            item = QtWidgets.QTableWidgetItem()
            item.setText(user['Nationality'])
            self.tableWidget.setItem(row, 1, item)

            item = QtWidgets.QTableWidgetItem()
            item.setText(str(user['Id']))
            self.tableWidget.setItem(row, 2, item)

        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TableTest"))
